org.gradle.jvmargs=-Xmx32G -Dnet.minecraftforge.gradle.check.certs=false

org.gradle.daemon=false

minecraft_version=1.20.1

minecraft_version_range=[1.20.1,1.21)

forge_version=47.2.0

forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=official

mapping_version=1.20.1

mod_id=BLACKSOULS II

mod_name=BLACKSOULS II

mod_license=LGPL-3.0
# The mod version. See https://semver.org/
mod_version=1.0.27
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=blacksouls.blacksoulsmod

mod_authors=HatsuYukiAya

mod_description=A fan-made RPG overhaul mod inspired by BlackSouls II, adding skills, combat systems, and story mechanics.

org.gradle.java.home=C:/Program Files/Java/jdk-17
