org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -Dnet.minecraftforge.gradle.check.certs=false

org.gradle.daemon=false

minecraft_version=1.20.1

minecraft_version_range=[1.20.1,1.20.2)

forge_version=47.2.0

forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=official

mapping_version=1.20.1

mod_id=blacksouls

mod_name=Black Souls II

mod_license=LGPL-3.0
# The mod version. See https://semver.org/
mod_version=2.0.1
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=blacksouls.blacksoulsmod

mod_authors=Bilibili_HatsuyukiAya

mod_description=A fan-made RPG overhaul mod inspired by BlackSouls II, adding skills, combat systems, and story mechanics.
